### ISSUE TITLE
npm module does not export anything

### ISSUE THREAD

**Issue by shahankit** [itajaja/url-matcher#1]
The published module on npm does not export anything in lib/index.js. When I import 'url-matcher' I get an empty object.

**Comment by petermikitsh** [comment]
I am also observing @shahankit's issue.

**Comment by petermikitsh** [comment]
I realized this was an issue when I tried using the module in Firefox 38 and it stumbled on the 'let' keyword.

**Comment by itajaja** [comment]
sorry @shahankit I totally missed your issue! I just released 0.2.2, which should fix your problem :)
